export interface Search{
    'id'?: number,
	'tipoidentificacion'?: string,
	'numero'?: number,
    'nombres'?: string,
    'apellidos'?: string,
	'direccion'?: string,
    'periodo'?: string,
    'anio'?: number,
    'mes'?: number,
    'valor'?: number,
    'valorfactura'?: number,
    'ultimafactura'?: number,
    'valorpagado'?: number,
    'estado'?: string,
}